# Generated by Django 2.1.7 on 2019-05-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaddfirstproject', '0002_candidateinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='CandDept',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
