# Generated by Django 2.1.7 on 2019-05-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultaddfirstproject', '0003_candidateinfo_canddept'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CanAddr', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateSalary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CanSalary', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
